---
group: "EL MEJOR GRUPO"
name: "dowloadfile2"
trigger:
  manual: true
  active: true
script: "dowloadfile2.groovy"
options:
  autosave: false
description: "no description found"
variables:
  key: "value"
credentials:
  - "qatecnico"
